### ISSUE TITLE
매장 조회 기능 구현

### ISSUE THREAD

**Issue by yenzip** [ddung-ddang/sttangbucks#2]
## 📄 Description
매장 목록 및 개별 조회 기능을 구현한다.

## ✅ Tasks
- [ ] API 명세서 작성
- [ ] 스타벅스 사이트에서 웹 크롤링을 통한 매장 정보 수집 및 데이터베이스 저장
- [ ] 매장과 관련된 도메인 객체 설계
- [ ] 매장 목록 조회 기능 구현
- [ ] 매장 단일 조회 기능 구현

## 🙋🏻 More
스타벅스의 전국 매장 수는 약 4만여 개로 매우 많기 때문에, 본 프로젝트는 **서울 내 매장(총 633개)으로만 한정**하여 진행합니다.
