### ISSUE TITLE
증정품(e-프리퀀시) 조회 기능 구현

### ISSUE THREAD

**Issue by yenzip** [ddung-ddang/sttangbucks#3]
## 📄 Description
증정품 목록 조회 및 개별 조회 기능을 구현한다.

## ✅ Tasks
- [ ] API 명세서 작성
- [ ] 증정품 데이터베이스 저장
- [ ] 증정품과 관련된 도메인 객체 설계
- [ ] 증정품 목록 조회 기능 구현
- [ ] 증정품 단일 조회 기능 구현
